name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          bash -n system/info/system_info.sh
          chmod +x system/info/system_info.sh
          ./system/info/system_info.sh
